[package]
name = "gh-pve-webhook"
version = "0.1.0"
edition = "2024"
publish = false

[profile.release]
strip = "symbols"

[lints.clippy]
large_futures = "deny"
enum_glob_use = "deny"

[dependencies]
aide = { version = "0.15.1", features = ["axum", "axum-json", "axum-query", "axum-tokio", "macros"] }
axum = "0.8.9"
bytes = "1.12.1"
chrono = "0.4.45"
color-eyre = "0.6.5"
config = "0.15.25"
derive_more = { version = "2.1.1", features = ["constructor", "display", "from", "into"] }
dotenvy = "0.15.7"
hex = "0.4.3"
hmac = "0.13.0"
http-body = "1.1.0"
http-body-util = "0.1.4"
mac_address = { version = "1.1.8", features = ["serde"] }
octocrab = "0.54.1"
pin-project-lite = "0.2.17"
proxmox-client = "0.9.2"
rand = "0.10.2"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.151"
serde_with = { version = "3.21.0", features = ["chrono_0_4", "schemars_0_9"] }
sha2 = "0.11.0"
thiserror = "2.0.19"
tokio = { version = "1.53", features = ["full"] }
tower-layer = "0.3.3"
tower-service = "0.3.3"
tracing = "0.1"
tracing-kickstart = { version = "0.9.0", features = ["exponential_histograms"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = { version = "2.5.8", features = ["serde"] }

[dev-dependencies]
tower = "0.5.3"
